### ISSUE TITLE
Random?

### ISSUE THREAD

**Issue by fredrikhaglund** [CMS18/Grupp7#1]
https://github.com/CMS18/Grupp7/blob/9f213ba21006f111c3b31662021509641c7aa200/Uppgift-2/Sudoku.cs#L181

Gillar inte Random - försök lösa uppgiften med en algorithm som systematiskt provar alla tal (använd loopar).

**Comment by Ronnehag** [comment]
Vi hade en vanlig for-loop innan, men blev oftast liknande/samma resultat om man körde ett bräde med endast nollor. Men skulle kunna ersätta den med en for-loop igen som testar.

**Comment by Ronnehag** [comment]
Korrigerat med en for-loop som sedan återgår till metod1 Solve()
