### ISSUE TITLE
Lösning för att gissa fungerar nog inte

### ISSUE THREAD

**Issue by fredrikhaglund** [CMS18/Grupp7#2]
https://github.com/CMS18/Grupp7/blob/9f213ba21006f111c3b31662021509641c7aa200/Uppgift-2/Sudoku.cs#L189

När man har gått igenom hela brädet utan att hitta en cell där det finns ett logiskt val (endast ett tal möjligt) är det dags att gissa.

När man gissar kan det bli fel. Därför måste man behålla originalet (så långt man kommit med lösningen) och göra en kopia av hela brädet. På denna kopia kan man föra in en gissning i en cell och försöka lösa det brädet. Hittar men lösning är man klar, annars måste man kast bort kopian, göra en ny kopia av originalet och föra in nästa gissning och försöka lösa det brädet.

**Comment by Ronnehag** [comment]
Du vill att vi behåller metoden från Uppgift1 och sedan lägger till denna rekursiva-metod i uppgift2?
Så att den först kör alla logiska tal, sen hoppas in i den rekursiva?
För nu fungerar den lite mer som brute-force.

**Comment by fredrikhaglund** [comment]
Ja, precis.

Skicka in ett olöst bräde i Solve. Fas 1 - fyll alla celler med logiska värden (endast ett tal möjligt) tills det inte längre går. Fas 2 - om brädet inte är löst, hitta en tom cell med fler möjliga värden för en cell och testa systematiskt ett tal åt gången.

**Comment by Ronnehag** [comment]
Korrigerat, lagt till metoden från Uppgift 1 och korrigerat lite i gissningen.
